start go run main.go
start go run service/favoriteaction/server.go
start go run service/favoritelist/server.go
start go run service/feed/server.go
start go run service/followaction/server.go
start go run service/followerlist/followerlistserver.go
start go run service/followlist/server.go
start go run service/login/loginServer.go
start go run service/publist/publistService.go
start go run service/register/server.go
start go run service/userinf/userinfService.go
start go run service/comment/server.go