// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CommentActionClient is the client API for CommentAction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentActionClient interface {
	CommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentAcitonResponse, error)
}

type commentActionClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentActionClient(cc grpc.ClientConnInterface) CommentActionClient {
	return &commentActionClient{cc}
}

func (c *commentActionClient) CommentAction(ctx context.Context, in *DouyinCommentActionRequest, opts ...grpc.CallOption) (*DouyinCommentAcitonResponse, error) {
	out := new(DouyinCommentAcitonResponse)
	err := c.cc.Invoke(ctx, "/douyin.extra.first.comment_action/comment_action", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentActionServer is the server API for CommentAction service.
// All implementations must embed UnimplementedCommentActionServer
// for forward compatibility
type CommentActionServer interface {
	CommentAction(context.Context, *DouyinCommentActionRequest) (*DouyinCommentAcitonResponse, error)
	mustEmbedUnimplementedCommentActionServer()
}

// UnimplementedCommentActionServer must be embedded to have forward compatible implementations.
type UnimplementedCommentActionServer struct {
}

func (UnimplementedCommentActionServer) CommentAction(context.Context, *DouyinCommentActionRequest) (*DouyinCommentAcitonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentAction not implemented")
}
func (UnimplementedCommentActionServer) mustEmbedUnimplementedCommentActionServer() {}

// UnsafeCommentActionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentActionServer will
// result in compilation errors.
type UnsafeCommentActionServer interface {
	mustEmbedUnimplementedCommentActionServer()
}

func RegisterCommentActionServer(s grpc.ServiceRegistrar, srv CommentActionServer) {
	s.RegisterService(&CommentAction_ServiceDesc, srv)
}

func _CommentAction_CommentAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinCommentActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentActionServer).CommentAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/douyin.extra.first.comment_action/comment_action",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentActionServer).CommentAction(ctx, req.(*DouyinCommentActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentAction_ServiceDesc is the grpc.ServiceDesc for CommentAction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentAction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "douyin.extra.first.comment_action",
	HandlerType: (*CommentActionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "comment_action",
			Handler:    _CommentAction_CommentAction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comment.proto",
}

// CommentListClient is the client API for CommentList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CommentListClient interface {
	CommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error)
}

type commentListClient struct {
	cc grpc.ClientConnInterface
}

func NewCommentListClient(cc grpc.ClientConnInterface) CommentListClient {
	return &commentListClient{cc}
}

func (c *commentListClient) CommentList(ctx context.Context, in *DouyinCommentListRequest, opts ...grpc.CallOption) (*DouyinCommentListResponse, error) {
	out := new(DouyinCommentListResponse)
	err := c.cc.Invoke(ctx, "/douyin.extra.first.comment_list/comment_list", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CommentListServer is the server API for CommentList service.
// All implementations must embed UnimplementedCommentListServer
// for forward compatibility
type CommentListServer interface {
	CommentList(context.Context, *DouyinCommentListRequest) (*DouyinCommentListResponse, error)
	mustEmbedUnimplementedCommentListServer()
}

// UnimplementedCommentListServer must be embedded to have forward compatible implementations.
type UnimplementedCommentListServer struct {
}

func (UnimplementedCommentListServer) CommentList(context.Context, *DouyinCommentListRequest) (*DouyinCommentListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommentList not implemented")
}
func (UnimplementedCommentListServer) mustEmbedUnimplementedCommentListServer() {}

// UnsafeCommentListServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CommentListServer will
// result in compilation errors.
type UnsafeCommentListServer interface {
	mustEmbedUnimplementedCommentListServer()
}

func RegisterCommentListServer(s grpc.ServiceRegistrar, srv CommentListServer) {
	s.RegisterService(&CommentList_ServiceDesc, srv)
}

func _CommentList_CommentList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinCommentListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CommentListServer).CommentList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/douyin.extra.first.comment_list/comment_list",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CommentListServer).CommentList(ctx, req.(*DouyinCommentListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CommentList_ServiceDesc is the grpc.ServiceDesc for CommentList service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CommentList_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "douyin.extra.first.comment_list",
	HandlerType: (*CommentListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "comment_list",
			Handler:    _CommentList_CommentList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "comment.proto",
}
