// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: followlist.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FollowListClient is the client API for FollowList service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FollowListClient interface {
	GetFollowList(ctx context.Context, in *DouyinRelationFollowListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowListResponse, error)
}

type followListClient struct {
	cc grpc.ClientConnInterface
}

func NewFollowListClient(cc grpc.ClientConnInterface) FollowListClient {
	return &followListClient{cc}
}

func (c *followListClient) GetFollowList(ctx context.Context, in *DouyinRelationFollowListRequest, opts ...grpc.CallOption) (*DouyinRelationFollowListResponse, error) {
	out := new(DouyinRelationFollowListResponse)
	err := c.cc.Invoke(ctx, "/douyin.extra.second.FollowList/GetFollowList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FollowListServer is the server API for FollowList service.
// All implementations must embed UnimplementedFollowListServer
// for forward compatibility
type FollowListServer interface {
	GetFollowList(context.Context, *DouyinRelationFollowListRequest) (*DouyinRelationFollowListResponse, error)
	mustEmbedUnimplementedFollowListServer()
}

// UnimplementedFollowListServer must be embedded to have forward compatible implementations.
type UnimplementedFollowListServer struct {
}

func (UnimplementedFollowListServer) GetFollowList(context.Context, *DouyinRelationFollowListRequest) (*DouyinRelationFollowListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetFollowList not implemented")
}
func (UnimplementedFollowListServer) mustEmbedUnimplementedFollowListServer() {}

// UnsafeFollowListServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FollowListServer will
// result in compilation errors.
type UnsafeFollowListServer interface {
	mustEmbedUnimplementedFollowListServer()
}

func RegisterFollowListServer(s grpc.ServiceRegistrar, srv FollowListServer) {
	s.RegisterService(&FollowList_ServiceDesc, srv)
}

func _FollowList_GetFollowList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DouyinRelationFollowListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FollowListServer).GetFollowList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/douyin.extra.second.FollowList/GetFollowList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FollowListServer).GetFollowList(ctx, req.(*DouyinRelationFollowListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FollowList_ServiceDesc is the grpc.ServiceDesc for FollowList service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FollowList_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "douyin.extra.second.FollowList",
	HandlerType: (*FollowListServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetFollowList",
			Handler:    _FollowList_GetFollowList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "followlist.proto",
}
