datasource:
  mysql:
    host : 123.57.194.129
    port : 3306
    database: chaossat
    username: root
    password: woshizhu
    charset: utf8
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    DB: 0
server:
  port: 80
